### ISSUE TITLE
Not working due to: No module named 'langchain_core.schema'

### ISSUE THREAD

**Issue by MarieOestreich** [ur-whitelab/chemcrow-public#14]
Installation and API key setup was done as described in the readme, but when running 

`from chemcrow.agents import ChemCrow`

I am getting the error

`ModuleNotFoundError: No module named 'langchain_core.schema'`

langchain is installed and version confirmed to be 0.0.275.

Thanks in advance!

**Comment by doncamilom** [comment]
Hi there! Thank you for your feedback.

The issue has been solved, can you try installing again with `pip install chemcrow -U`

The problem was the `langchain_core` library which wasn't pinned and was simply pointing to the newest (0.0.6) that has no `langchain_core.schema` module, while the first version (0.0.1) does.
