### ISSUE TITLE
  ERROR: Failed building wheel for molbloom

### ISSUE THREAD

**Issue by docmab23** [ur-whitelab/chemcrow-public#6]
Got this error while simply installing using PIP 

![image](https://github.com/ur-whitelab/chemcrow-public/assets/31487695/f20de89d-3c4b-4bff-b9aa-1b4e8d7825f4)

**Comment by whitead** [comment]
Is this windows?

**Comment by praveenexaf** [comment]
Yes!

**Comment by imran-mdkhan197** [comment]
Is this issue fixed ? Any work around for using chemcrow on Windows ?

**Comment by praveenexaf** [comment]
I dont think so... I used wsl to run it on my windows pc

**Comment by benderill** [comment]
Having the same issue

**Comment by SamCox822** [comment]
This is an issue with molbloom's current incompatibility with windows (see [here](https://github.com/whitead/molbloom/issues/8)). We're not sure how to solve this on our end just yet for windows. 

This issue may arise with python 3.12, even for Mac users. Until it's fixed in the molbloom package, we restrict the python versions to below 3.12 as a quick fix. This likely will not fix the windows problem, however.

**Comment by SamCox822** [comment]
solved here - https://github.com/whitead/molbloom/issues/8 closing
